[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "control-flow-guard=checks",
    "-C", "link-arg=/CETCOMPAT",
    "-C", "link-arg=/DYNAMICBASE",
    "-C", "link-arg=/HIGHENTROPYVA",
    "-C", "link-arg=/NXCOMPAT",
]
